#!/bin/bash
# Script for running Judge0 server.
#
# Usage: ./scripts/server
#
echo "scripts/server:Starting server..."
source ./scripts/load-config
export | sudo tee /api/environment

for i in $(seq 1 $RESTART_MAX_TRIES); do
    [[ -f tmp/pids/server.pid ]] && rm -f tmp/pids/server.pid

    rails db:create db:migrate db:seed
    if [[ $? -eq 0 ]]; then
        echo "Database setup successful."
        break
    else
        echo "Database setup failed, retrying..."
    fi
    sleep 2s
done

echo "Starting Rails server..."
rails s -b 0.0.0.0
